moved iana urn registration template as directed
ietf-wg-uuidrev/rfc4122bis pull request #35
Opened 2022-12-13 00:35 UTC by bradleypeabody

@kyzer-davis here's my attempt to address #23.  Some of the text I was able to just move over from what you had there but some fields didn't have a corresponding place in the new template so I just filled it out based on what made sense to me.

2023-01-17 04:56 UTC, jimfenton reviewed
Corrections to ABNF (should be consistent with Section 4)

2023-01-17 04:56 UTC, jimfenton commented on draft-ietf-uuidrev-rfc4122bis.md
> +node                   = 6hexOctet
```suggestion
node                   = 6*hexOctet
```

2023-01-17 04:56 UTC, jimfenton commented on draft-ietf-uuidrev-rfc4122bis.md
> +time-high-and-version  = 2hexOctet
```suggestion
time-high-and-version  = 2*hexOctet
```

2023-01-17 04:56 UTC, jimfenton commented on draft-ietf-uuidrev-rfc4122bis.md
> +time-mid               = 2hexOctet
```suggestion
time-mid               = 2*hexOctet
```

2023-01-17 04:56 UTC, jimfenton commented on draft-ietf-uuidrev-rfc4122bis.md
> +time-low               = 4hexOctet
```suggestion
time-low               = 4*hexOctet
```

2023-01-19 19:24 UTC, mcr commented on draft-ietf-uuidrev-rfc4122bis.md
> +  provided by the following ABNF {{RFC4234}}:
```suggestion
  provided by the following ABNF {{RFC5234}}:
```

2023-01-19 19:27 UTC, mcr requested changes

2023-01-19 19:27 UTC, mcr commented on draft-ietf-uuidrev-rfc4122bis.md
> +  provided by the following ABNF {{RFC4234}}:
Maybe the ABNF could be referenced to this document, rather than repeated in the template.

2023-01-20 18:03 UTC, merged