add two more methods to the monotonic section
ietf-wg-uuidrev/rfc4122bis pull request #81
Opened 2023-04-09 17:55 UTC by bradleypeabody

After reading through everything again, while the monotonic/counter section works as it stands now, I think it would greatly benefit from two other specific suggested methods for achieving monotonicity.

The first I think is beneficial because it is trivial to implement (just keep generating random values until you get one that is greater than the last), and implementors prioritizing simplicity would benefit from it.

And the second brings back a concept that I originally proposed in the initial draft for UUID v7 (using later bits in the UUID to encode more timestamp precision in a way that time ordered), but later removed because it was often misunderstood.  However, I think the key benefit to this approach (just using the additional precision available in the system clock for what it's mean for) still exists and makes sense, and having it here as an optional feature so implementations are not required to understand and use it if they don't need to - I believe that tradeoff makes a lot of sense.  I tried to keep it super simple by just giving an example of how to use it, and people can infer the underlying math/theory or not as needed.

2023-04-09 18:16 UTC, bradleypeabody commented on draft-ietf-uuidrev-rfc4122bis.md
> +with high frequency UUID generation.
This is the same edit from here https://github.com/ietf-wg-uuidrev/rfc4122bis/pull/79#discussion_r1161177270

2023-04-10 22:25 UTC, jimfenton requested changes
Mostly editorial fixes suggested; I think we need more input on this. They both need to be expressed in normative language

Method 4 mixes the normative requirements with an example. Suggest pulling the example into one or more separate paragraphs so the reader can distinguish between what they are required to do and the example of how to do it.

2023-04-10 22:25 UTC, jimfenton commented on draft-ietf-uuidrev-rfc4122bis.md
> +  of implementation. The down sides to this approach include the fact that
```suggestion
  of implementation. One downside to this approach is the fact that
```

2023-04-10 22:25 UTC, jimfenton commented on draft-ietf-uuidrev-rfc4122bis.md
> +  generation will become increasing slow for a given timestamp value as
```suggestion
  generation will become increasingly slow for a given timestamp value as
```

2023-04-10 22:25 UTC, jimfenton commented on draft-ietf-uuidrev-rfc4122bis.md
> +  more attempts are required to product monotonic output, and the fact that
```suggestion
  more attempts are required to produce monotonic output, and the fact that
```

2023-04-11 01:14 UTC, bradleypeabody commented
@jimfenton Thanks for the feedback, I did the edits you suggested and split up Method 4 into a few paragraphs and added a normative description as you suggest.  Let me know if there's anything else you think I should adjust immediately and otherwise I agree it would be good to get more feedback from others and go from there.

2023-04-11 14:17 UTC, kyzer-davis commented
Verified Method 3 and 4 render properly with author-tools in HTML/TXT formats. Merging down.

2023-04-11 14:17 UTC, merged